# docker-composeのバージョン指定


# コンテナ群の記述
services:
  # nginxというサービス
  nginx:
    # コンテナ名指定
    container_name: curriculum-nginx
    # 使用イメージの指定
    image: nginx:latest
    # 同期ファイルの指定
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - ./app:/var/www/html
    # 使用ポートの指定
    ports:
      - "80:80"
    # 依存関係の指定 (指定したコンテナより後に立ち上がる)
    depends_on:
      - php

  php:
    container_name: curriculum-laravel
    ###############################################################
    # Mac M1チップユーザーは以下のコメントアウトを解除して作業を進めてください
    # platform: linux/x86_64
    ###############################################################
    
    # どれを使ってビルド(コンテナ立ち上げを行うか)
    build:
      # ディレクトリの指定
      context: ./
      # 使用するDockerfile名の指定
      dockerfile: docker/php/Dockerfile
    volumes:
    - ./app:/var/www/html
    - ./docker/php/check_startup.sh:/tmp/check_startup.sh
    # サーバーに対してオープンするポートを指定
    expose:
      - "9000"
    depends_on:
      - db

    command: |
      bash -c "

      if [ ! -f /var/www/html/.env ]; then
        echo '.env file not found. Creating from .env.example...' && \
        cp /var/www/html/.env.example /var/www/html/.env && \
        sed -i 's/DB_HOST=.*/DB_HOST=db/' /var/www/html/.env && \
        sed -i 's/DB_PASSWORD=.*/DB_PASSWORD=root/' /var/www/html/.env
      else
        echo '.env file already exists.';
      fi
      # MySQLの準備を待つ
      until mysql -h db -u root -proot -e 'SELECT 1'; do
        echo 'Waiting for MySQL to be ready...'
        sleep 2
      done
      # Laravelのマイグレーションとビルド
      npm install sass@latest && \
      composer install && \
      composer update && \
      composer dump-autoload && \
      php artisan key:generate && \
      php artisan storage:link && \
      chown -R www-data storage/ && \
      php artisan cache:clear && \
      npm install && \
      npm run build && \
      php artisan migrate --force --no-interaction && \
      php artisan db:seed --class=usersTableSeeder && \
      php artisan db:seed --class=forumsTableSeeder && \
      composer require pusher/pusher-php-server && \
      php-fpm"
      tty: true

  db:
    container_name: curriculum-db
    image: mysql:5.7
    # コンテナの環境変数を指定
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'
    volumes:
      - ./db:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306

  phpMyAdmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_PARBIRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    # コンテナの関連を指定
    links:
      - db
    ports:
      - 4040:80
    volumes:
      - ./phpmyadmin/sessions:/sessions

      # docker-compose command:でコマンド作成可能